# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

workspace:
  clean: all   # Full cleanup before build

steps:
- checkout: self
  clean: true  # Ensures fresh code from repo

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: |
    chmod +x node_modules/.bin/playwright
    npx playwright install --with-deps
  displayName: 'Playwright install'

- script: |
    sudo apt-get update
    sudo apt-get install -y maven
  displayName: 'Install Maven'

- script: |
    mvn test -Denv=preprod -Dbrand=vans -Dregion=ca -Dtag=@Vans_CA_Smoke12
  displayName: 'Execute new script'