
trigger:
- main

pool:
  vmImage: ubuntu-latest

workspace:
  clean: all   # Full cleanup before build

steps:
- script: |
    echo "Building commit:"
    git rev-parse HEAD
  displayName: 'Show current commit'

- script: |
    mkdir -p screenshorts
  displayName: 'Create screenshorts directory'

- checkout: self
  clean: true  # Ensures fresh code from repo

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

- script: |
    chmod +x node_modules/.bin/playwright
    npx playwright install --with-deps
  displayName: 'Playwright install'

- script: |
    sudo apt-get update
    sudo apt-get install -y maven
  displayName: 'Install Maven'

- script: |
    mvn test -Denv=preprod -Dbrand=vans -Dregion=ca -Dtag=@Vans_CA_Smoke2
  displayName: 'Execute new script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'screenshorts'
    artifact: 'test-screenshorts'
  condition: succeededOrFailed()
  displayName: 'Publish test Screenshorts'
